'use strict';
// const faker = require('faker');

module.exports = {
    up : async (queryInterface, Sequelize)=>{
      await queryInterface.sequelize.query("ALTER TABLE default_fees_and_rewards AUTO_INCREMENT = 1;");
      
 
      return queryInterface.bulkInsert('default_fees_and_rewards', [
        {
        options: 'Ad Lover',
        percentage: '0',
        entry_fee: '0',
        win_reward: '5',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/33499646460980845471.01_Ad-lover_gift_box_icon_pink_FF6699.svg',
        color_code: '#FF6699',
        game_mode: 'Training',
        unit: 'lt',
        bot_speed_from: '80',
        bot_speed_to: '100',
        bot_correct_answer_from: '10',
        bot_correct_answer_to: '50',
        bot_error_from: '50',
        bot_error_to: '90',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Standard',
        percentage: '0',
        entry_fee: '5',
        win_reward: '9',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/50733816237403558919.02_Standard_acorn_icon_light_orange_F4B180.svg',
        color_code: '#F4B183',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '80',
        bot_speed_to: '100',
        bot_correct_answer_from: '10',
        bot_correct_answer_to: '50',
        bot_error_from: '50',
        bot_error_to: '90',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Starter',
        percentage: '20',
        entry_fee: '10',
        win_reward: '18',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/17957941336125614647.03_Starter_cube_icon_grey.svg',
        color_code: '#C9C9C9',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '80',
        bot_speed_to: '100',
        bot_correct_answer_from: '10',
        bot_correct_answer_to: '50',
        bot_error_from: '50',
        bot_error_to: '90',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Climber',
        percentage: '40',
        entry_fee: '50',
        win_reward: '90',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/47501316109244568589.04_Climber_icon_blue_grey_8497B0.svg',
        color_code: '#8497B0',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '60',
        bot_speed_to: '80',
        bot_correct_answer_from: '50',
        bot_correct_answer_to: '70',
        bot_error_from: '30',
        bot_error_to: '50',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Skilled',
        percentage: '60',
        entry_fee: '100',
        win_reward: '180',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/29385752909336534779.05_1_Skilled_star_icon_dark_teal_006666.svg',
        color_code: '#006666',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '40',
        bot_speed_to: '60',
        bot_correct_answer_from: '70',
        bot_correct_answer_to: '85',
        bot_error_from: '15',
        bot_error_to: '30',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Expert',
        percentage: '80',
        entry_fee: '500',
        win_reward: '900',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/62755405053409598781.06_1_Expert_gearman_icon_red_FF5050.svg',
        color_code: '#FF5050',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '30',
        bot_speed_to: '40',
        bot_correct_answer_from: '85',
        bot_correct_answer_to: '90',
        bot_error_from: '10',
        bot_error_to: '15',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Savant',
        percentage: '90',
        entry_fee: '1000',
        win_reward: '1800',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/82722264005993376052.07_Savant_knight_helmet_icon_purple_660066.svg',
        color_code: '#660066',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '20',
        bot_speed_to: '30',
        bot_correct_answer_from: '90',
        bot_correct_answer_to: '99',
        bot_error_from: '1',
        bot_error_to: '10',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        {
        options: 'Joker',
        percentage: '95',
        entry_fee: '5000',
        win_reward: '9000',
        icon: 'https://zleetz-assets.s3.eu-north-1.amazonaws.com/content/matchTokenImage/24187285158708514662.08_Joker_icon_dark_yellow_CCCC00.svg',
        color_code: '#CCCC00',
        game_mode: 'Training',
        unit: 'LT',
        bot_speed_from: '10',
        bot_speed_to: '20',
        bot_correct_answer_from: '100',
        bot_correct_answer_to: '100',
        bot_error_from: '0',
        bot_error_to: '0',
        status: '1',
      created_at : new Date(),
      updated_at : new Date(),
      },
        
    ],{} );
    
  },

  down :  (queryInterface, Sequelize) =>{
      return queryInterface.bulkDelete('default_fees_and_rewards', );
  }
};
